runmode: debug              # 开发模式， debug, release, test 
addr: :8080                 # 端口
name: blog 
url: http://127.0.0.1:8080  # pingServer函数请求的API服务器的ip:port
max_ping_count: 10          # pingServer函数尝试的次数
jwt_secret: r9c4xDC45tmvqvbV*w^AG^Ik
log:
  writers: file,stdout
  logger_level: DEBUG
  logger_file: log/app.log
  log_format_text: false
  rolling_policy: size
  log_rotate_date: 1
  log_rotate_size: 1
  log_backup_count: 7
db:
  name: blog
  addr: 127.0.0.1
  username: root
  password: root
gormlog: true 
tls:
  addr: :8081
  cert: conf/server.crt
  key: conf/server.key